### ISSUE TITLE
Tilemap.py feature request from Tiled

### ISSUE THREAD

**Issue by humansHS** [pvcraven/arcade#580] opened 2020-02-04 15:05 UTC
## Enhancement request:
It would be good if tilemap.py could output rotated tiles. Also, it appears that currently there is implementation of 'flipped' tiles but it does not work (see attached files).

This would be an extension of pytiled_parser I presume.

### What should be added/changed?
Rotated tiles from Tiled being rotated sprites.
Flipped tiles from Tiled being flipped sprites.

### What would it help with?
The feature exists in Tiled. It reduces the amount of work and space taken by having several tile images created for different rotations/sides where just one can be used.

![tilemaprequest](https://user-images.githubusercontent.com/57516846/73754860-fba80780-47b4-11ea-8119-c6c98b69c31e.png)

**Comment by pvcraven** [comment] 2020-02-04 15:16
Yes! I'd love to see support of rotated tiles.
Duplicate of issue #375, which is currently on the list of desired enhancements:
http://arcade.academy/enhancement_list.html

**Comment by pvcraven** [comment] 2020-02-04 15:16
And thanks for your request, with detailed images.

**Closed by pvcraven** 2020-02-04 15:16 UTC
