### ISSUE TITLE
tiled map doesn't display the left-most and bottom most row of tiles

### ISSUE THREAD

**Issue by jsantore** [pvcraven/arcade#503] opened 2019-10-09 02:34 UTC
## Bug Report
using the arcade v2 tiled map bottom row and left column are not displayed.

### Actual behavior:

the bottom most row and left most column of the map do not display on the window. 

### Expected behavior:

all ten columns and rows of a 10x10 map show up on the window.

### Steps to reproduce/example code:
create, call setup, and then arcade run, using the window class below.
map3.tmx is a 10x10 orthogonal map created by tiled using 64x64 pixel tile images.

```
import arcade
import pathlib
class TiledWindow (arcade.Window):
    def __init__(self):
        super().__init__(640, 640, "Initial Tiled Map Super Simple Example")
        self.map_location = pathlib.Path.cwd()/'Assets'/'map3.tmx'
        self.maplist = None

    def setup(self):
        sample__map = arcade.tilemap.read_tmx(str(self.map_location))
        self.maplist = arcade.tilemap.process_layer(sample__map, "map_layer", 1)

    def on_draw(self):
        arcade.start_render()
        self.maplist.draw()
```

## Enhancement request:

please fix

### What should be added/changed?

not sure if this is the way you want to go, but in the tilemap.py, in the _process_tile_layer function, lines 283 & 284 read:

```
my_sprite.right = column_index * (map_object.tile_size[0] * scaling)
my_sprite.top = (map_object.map_size.height - row_index - 1) * (map_object.tile_size[1] * scaling)
```

if you change that to 

```
my_sprite.left = column_index * (map_object.tile_size[0] * scaling)
my_sprite.bottom = (map_object.map_size.height - row_index - 1) * (map_object.tile_size[1] * scaling)
```

then it works and the entire map displays

### What would it help with?

not having to put a hacky extra dummy row and column into map files.

**Comment by SirGnip** [comment] 2019-10-09 02:50
Dupe of #415 (You can see a workaround in the example code in #415.  Simply, you loop over the tiles and offset their x/y manually.)

**Comment by SirGnip** [comment] 2019-10-11 03:26
While reading through this bug, I made another observation,  In the `examples/platform_tutorial/09_endgame.py` example game, I noticed that the coins in the game are slightly offset from what the Tiled map editor shows, beyond the one-tile offset mentioned in the bug report above.  Screenshots below were taken with a dev build of arcade at 9076043.

Map `map2_level_1.tmx` in tiled editor:
![image](https://user-images.githubusercontent.com/5678175/66621705-baa73a00-ebaa-11e9-9280-48e21fc10bed.png)

Map as seen during `examples/platform_tutorial/09_endgame.py` running:
![image](https://user-images.githubusercontent.com/5678175/66622086-09090880-ebac-11e9-9880-7173a6ec7bd1.png)

Notice how the coins in game seem to be a bit higher and to the right of what the Tiled map editor shows?  You can see the coin to the right of the arrow sign is clearly below the arrow's point in Tiled, but is above the arrow's point in the game.  Also, the coin in the middle of the first-highest platform is obviously centered in Tiled, but in-game it is offset slightly to the right (and up).  These offsets are not whole-tile offsets, but much less than that.

I guess it is possible that the coins are in the right place and the platforms are shifted, etc?  I don't know enough about the map code to efficiently start digging into this one, but wanted to document what I saw...

**Comment by pvcraven** [comment] 2019-10-24 19:23
If the tile isn't the same size as the grid, everything is all messed up.

**Comment by pvcraven** [comment] 2019-10-25 18:32
Closing. Things should work ok in the latest release. Reopen if you spot a bug.

**Closed by pvcraven** 2019-10-25 18:32 UTC
Labels: bug
