### ISSUE TITLE
draw_text issue

### ISSUE THREAD

**Issue by l0stmind** [pvcraven/arcade#477] opened 2019-09-01 20:10 UTC
well i just installed arcade lib on my comp, but i have a problem with drawing text:
![](https://i.redd.it/5dpigzu2p0k31.jpg)
When i run the drawing text example from the site, the windows show up with the blue dot but no text.

when i close the program the console return the capture screen upward.

I have tried the starting template and it work ok.

have you any idea on what is going on?

I actually run Python 3.7 and have installed arcade throught pip and my OS is Win7

Thanks for any help!

**Comment by pvcraven** [comment] 2019-09-02 15:30
Interesting. Do the other examples work? Like the asteroid game?

**Comment by l0stmind** [comment] 2019-09-02 17:06
Hello Mr Craven, thanks for your time,
well the asteroid game start and run (don't stop and crash)
On exit the console return that:

`Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "C:\Users\mel\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyglet\window\win32\__init__.py", line 641, in f
    result = event_handler(msg, wParam, lParam)
  File "C:\Users\mel\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyglet\window\win32\__init__.py", line 934, in _event_close
    self.dispatch_event('on_close')
  File "C:\Users\mel\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyglet\window\__init__.py", line 1330, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Users\mel\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyglet\event.py", line 407, in dispatch_event
    if getattr(self, event_type)(*args):
  File "C:\Users\mel\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyglet\window\__init__.py", line 812, in on_close
    self.close()
  File "C:\Users\mel\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyglet\window\win32\__init__.py", line 307, in close
    super(Win32Window, self).close()
  File "C:\Users\mel\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyglet\window\__init__.py", line 834, in close
    self._context.destroy()
  File "C:\Users\mel\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyglet\gl\base.py", line 366, in destroy
    self.detach()
  File "C:\Users\mel\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyglet\gl\win32.py", line 248, in detach
    wgl.wglDeleteContext(self._context)
OSError: exception: access violation reading 0x00000122
`
when the game run i have garbled graphics of the that distord according the direction key i use :
![image](https://user-images.githubusercontent.com/12373426/64127962-3f38b880-cdb4-11e9-85f9-d10a608c7f21.png)

then when i close the main arcade windows(not the console): i got that:
![image](https://user-images.githubusercontent.com/12373426/64128000-76a76500-cdb4-11e9-9358-0cd35a1357cf.png)

So the console freeze and i must close it with the red cross button.

Surely a Pyglet issue i think.
Well thats it hope it help....
I will try another way to use python to display stuff....
see you, ludo

**Comment by pvcraven** [comment] 2019-09-02 18:01
Holy cow. Do you have Pyglet 1.4.2? I've not seen anything quite like this.

**Comment by l0stmind** [comment] 2019-09-02 19:17
Confirmed 1.4.2 according to pip list:
![image](https://user-images.githubusercontent.com/12373426/64131125-e6265000-cdc6-11e9-8921-5910bffef23d.png)
thank and see you

**Comment by l0stmind** [comment] 2019-09-02 19:27
Another thing i didn't notice when i post one our ago, when exiting arcade app the console freeze so i let it open and then have my dish...
When i came back the console seem to have recovered and i have now that:
(it is the same launch from my previous post, same cmd windows)
 
![image](https://user-images.githubusercontent.com/12373426/64131340-4073e080-cdc8-11e9-8797-9b80e5af59ee.png)

Hope it could help you!
See you mr Craven

**Comment by pvcraven** [comment] 2019-09-02 20:24
If glDeleteVertexArrays isn't supported by your OpenGL driver, I'm guessing
you have an older version of OpenGL, but the start-up isn't, for some
reason, recognizing that it is older.
Paul Vincent Craven

**Comment by pvcraven** [comment] 2020-01-27 15:44
Unable to reproduce. Closing. Feel free to re-open if more info comes up.

**Closed by pvcraven** 2020-01-27 15:44 UTC
Labels: bug
