### ISSUE TITLE
"AttributeError: 'NoneType' object has no attribute 'flatten'" while calling any function from arcade.draw_commands

### ISSUE THREAD

**Issue by ThePolishMUSIC** [pvcraven/arcade#353] opened 2019-04-15 09:58 UTC
I'm using 64-bit Python 3.7.3 on Windows 10. When I try to call any function from `arcade.draw_commands`, it raises AttributeError:
```Traceback (most recent call last):
  File "C:/Users/User/PycharmProjects/something in pyglet/main.py", line 179, in <module>
    pyglet.app.run()
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\pyglet\app\__init__.py", line 142, in run
    event_loop.run()
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\pyglet\app\base.py", line 175, in run
    self._run()
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\pyglet\app\base.py", line 187, in _run
    timeout = self.idle()
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\pyglet\app\base.py", line 314, in idle
    window.dispatch_event('on_draw')
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\pyglet\window\__init__.py", line 1313, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\pyglet\event.py", line 361, in dispatch_event
    if handler(*args):
  File "C:/Users/User/PycharmProjects/something in pyglet/main.py", line 152, in on_draw
    player.draw(player.x - camera.x, player.y - camera.y, 50)
  File "C:/Users/User/PycharmProjects/something in pyglet/main.py", line 100, in draw
    draw_commands.draw_line(x, y, x+50, y+50, (255, 255, 255), 5)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\arcade\draw_commands.py", line 838, in draw_line
    _generic_draw_line_strip(triangle_point_list, color, gl.GL_TRIANGLE_STRIP)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\arcade\draw_commands.py", line 763, in _generic_draw_line_strip
    program['Projection'] = get_projection().flatten()
AttributeError: 'NoneType' object has no attribute 'flatten'```

Functions that raised the error (note: every one is in the function `draw(x, y, size)`):
```draw_commands.draw_line(x, y, x+50, y+50, (255, 255, 255), 5)
draw_commands.draw_circle_filled(x, y, size, (255, 255, 255))
draw_commands.draw_arc_filled(x, y, size, size, (255, 255, 255), 0, 90, 0, 90)
ect, ect...
```
I don't know what causes such behaviour.

**Comment by pvcraven** [comment] 2019-04-15 23:50
Hard to tell without a full example. It could be caused by not opening a window before trying to draw.

**Comment by pvcraven** [comment] 2019-04-22 17:22
Closing. Please re-open if more info is added.

**Closed by pvcraven** 2019-04-22 17:22 UTC
