### ISSUE TITLE
Cannot run the Sprite Tiled Map example.

### ISSUE THREAD

**Issue by carlsmith** [pvcraven/arcade#262] opened 2018-07-29 19:56 UTC
I used the following command to run the Sprite Tiled Map example:

``` sh
python3 -m arcade.examples.sprite_tiled_map
```

### Actual behavior:

The program tries to open a window, but then crashes out, with the following error message:

```
FileNotFoundError: [Error 2] No such file or directory: 'map.csv'
```

The exception occurs on Line 37, inside `arcade/examples/sprite_tiled_map.py`

### Expected behavior:

The example game fires up.

### Steps to reproduce/example code:

Run the command.

**Comment by pvcraven** [comment] 2018-07-29 22:01
Duplicate of #248. Fixed in master branch, will be part of the next release. In the meantime, you can grab from GitHub. Sorry for the inconvenience.

**Closed by pvcraven** 2018-07-29 22:01 UTC
Labels: duplicate
