### ISSUE TITLE
All update() methods should have a delta_time parameter

### ISSUE THREAD

**Issue by SirGnip** [pvcraven/arcade#300] opened 2019-02-03 21:37 UTC
### Actual behavior:
There is an inconsistency in the signature of `update()` methods across the arcade library.  `Window` and `ArcadeWindow` have an `update()` method that accepts a float parameter named `delta_time`.  Other classes that have an `update()` method (which are often called from within `Window.update()`), do not accept a `delta_time` parameter.

### Expected behavior:
Any `update()` methods that deal with "stepping the world", such as updating positions, advancing animations or driving simulations should accept a `delta_time` parameter to be consistent with `Window.update()`.  This allows games to pass `delta_time` from `Window.update()` down into the `update()` methods of sub-objects such as `Sprite.update()` and `SpriteList.update()` so that those objects can also make use of `delta_time`.

### Details (tl;dr)
Having `delta_time` available in most `update()` methods allows games to use a time-based game loop for motion, animation and simulations. (Google "frame-based vs time-based game loops" for discussion and pros/cons) .  It also allows the game developer to choose either approach (ignore delta_time to take a frame-based approach or use delta_time to take a time-based approach).  Granted it is a bit more complex for games to implement time-based game loops, which may not be desirable for an education-focused library.  And, this would potentially require changes in the implementation of methods like Sprite.update() to look something like this:

```
    def update(self, delta_time: float):
        self.set_position(self.center_x + (self.change_x * delta_time), self.center_y + (self.change_y * delta_time))
        self.angle += self.change_angle * delta_time
```
This would also change the implied unit of `change_x`, depending on whether you tried to do a frame-based vs time-based game loop.  In tick-based game loops, the implied unit of `change_x` is "change in x per simulation step".  Where, in time-based game loops, `change_x` usually represents something like "change in x per second".

Even if the implementation of `update()` methods currently assume a frame-based game loop (like `Sprite.update()` currently is), I think there is still value in at least adding "delta_time" to the update() signatures for consistency's sake... and so that game developers can make their own choice (overriding 
implementations as necessary).

### Methods (at first glance) that are inconsistent with `Window.update()`:

* `Sprite.update()` : https://github.com/pvcraven/arcade/blob/master/arcade/sprite.py#L560
* `SpriteList.update()` : https://github.com/pvcraven/arcade/blob/master/arcade/sprite_list.py#L294
* `PhysicsEngineSimple.update()` : https://github.com/pvcraven/arcade/blob/master/arcade/physics_engines.py#L26

**Comment by pvcraven** [comment] 2019-02-09 16:03
I've kept it the way it is now for backwards compatibility. Ideally, they'd all have delta-time, except maybe updating the physics engine. I've learned from PyMunk that discrete update steps, rather than variable ones, work better.

**Comment by SirGnip** [comment] 2019-02-11 23:11
Understood.  Regarding adding time_delta and preserving backwards compatibility, you could always support two methods (ex: "update()" and "update_td(time_delta)" and do something dynamic like this to call them:

```
if hasattr(obj, "update_td"):
    obj.update_td(time_delta)
else:
    obj.update()
```

If it is ever decided to do any changes that break backwards compatability (v3.0?), passing time_delta into all update() methods has my vote.

**Comment by beling** [comment] 2019-02-12 13:59
I agree that updates should have delta_time. Maybe 2.0 release is a good moment for a breaking change (the earlier the better).

I teach Arcade during programming classes at University of Łódź. It is great for education (Thank you for your great work!).
That is why it should be consistent. As a teacher, I always have to comment all inconsistency (losing time).

**Comment by beling** [comment] 2019-02-14 23:02
I think that the application (game) should eventually clamp or even fix dalta_time in top-level update if something (like physics engine) cannot e.g. handle too large delta_time.

**Comment by pvcraven** [comment] 2019-04-27 17:11
This is a duplicate of #266 I think.

**Comment by pvcraven** [comment] 2020-01-17 22:22
Closing, dupe of #266. There is now in the dev code an `on_update` method with a sprite that has delta-time.

**Closed by pvcraven** 2020-01-17 22:22 UTC
Labels: enhancement
