### ISSUE TITLE
Fading text causes slow-down

### ISSUE THREAD

**Issue by MrGallo** [pvcraven/arcade#562] opened 2020-01-25 01:43 UTC
Fading out text causes slowdowns because the cache name includes the alpha value and it creates a new text sprite every loop for each alpha level.

Suggestion: only include the rgb values in the cache name, and set `text_sprite.alpha` to that new incoming alpha value.

**Comment by pvcraven** [comment] 2020-01-25 19:20
Fix for this broke typing checks.

**Comment by MrGallo** [comment] 2020-01-25 20:43
I don't understand the typing issue lol.

**Comment by pvcraven** [comment] 2020-01-26 00:23
Closed with release of 2.2.7.

**Closed by pvcraven** 2020-01-26 00:23 UTC
Labels: enhancement, fix waiting for release

**Comment by pvcraven** [comment] 2020-01-26 00:25
@MrGallo , the typing issue was caused by the function get_4_byte_color or whatever it is called returning a Color type. Because Color can be 3 or 4 bytes, it can't always be unpacked into 4 bytes. Doing a cast and changing the return type to RGBA (which is always 4 bytes) fixed the issue.
